image: node

pages:
  variables:
    TIDDLYWIKI_PLUGIN_PATH: plugins
  script:
    - npm install -g tiddlywiki
    # Generate as index.html: single HTML demo page
    - tiddlywiki editions/asciidoctordemo --build index
    # Generate as .json file: drag-n-drop installer for single HTML
    - tiddlywiki editions/asciidoctordemo --savetiddler '$:/plugins/bimlas/asciidoctor' tw5-asciidoctor.json
    # Generate as .tid file: drag-n-drop installer for node version
    # DOES NOT WORKS - exports as JSON
    # - tiddlywiki editions/asciidoctordemo --savetiddler '$:/plugins/bimlas/asciidoctor' tw5-asciidoctor.tid
    # GitLab needs 'public' dirname for deploy
    # https://gitlab.com/gitlab-org/gitlab-ee/issues/1719
    - mv editions/asciidoctordemo/output public
  artifacts:
    paths:
    - public
