image: node

pages:
  script:
    - git clone --depth 1 https://github.com/Jermolene/TiddlyWiki5 tw5
    - cp -r editions plugins tw5
    - cp -r editions tw5
    - node tw5/tiddlywiki.js tw5/editions/asciidoctordemo --build index
    # GitLab needs 'public' dirname for deploy
    # https://gitlab.com/gitlab-org/gitlab-ee/issues/1719
    - mv tw5/editions/asciidoctordemo/output public
  artifacts:
    paths:
    - public
